version: "3.8"
services:
  pgsql:
    container_name: "shopping-board-pgsql"
    image: "postgres:13.4-alpine"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      #      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_DB: ${DB_NAME:-shopping-board}
